name: cloudflared_tunnel_android_x86
description: Android x86 sidecar package for cloudflared_tunnel_full with x86 and x86_64 native libraries.
version: 1.0.0
homepage: https://github.com/lekoOwO/cloudflared_flutter
repository: https://github.com/lekoOwO/cloudflared_flutter
issue_tracker: https://github.com/lekoOwO/cloudflared_flutter/issues
documentation: https://github.com/lekoOwO/cloudflared_flutter/tree/main/packages/cloudflared_tunnel_android_x86#readme

environment:
  sdk: ^3.0.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cloudflare.cloudflared_tunnel_android_x86
        pluginClass: CloudflaredTunnelAndroidX86Plugin